### ISSUE TITLE
Crashed on signing up new account

### ISSUE THREAD

**Issue by Hikkihiki** [WikiLogic/Server#162]
To reproduce the issue:
1. Click "SIGNUP"
2. Enter new email account and password
3. Observe the following crash in browser

``` text
Error: Failed to lookup view "common/profile" in views directory "./views"
   at EventEmitter.app.render (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/application.js:555:17)
   at ServerResponse.res.render (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/response.js:938:7)
   at /Users/Hoiy/project/WikiLogic/controllers/index.js:100:7
   at Layer.handle [as handle_request] (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/router/layer.js:82:5)
   at next (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/router/route.js:110:13)
   at hasAccess (/Users/Hoiy/project/WikiLogic/controllers/index.js:117:16)
   at Layer.handle [as handle_request] (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/router/layer.js:82:5)
   at next (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/router/layer.js:82:5)
   at /Users/Hoiy/project/WikiLogic/node_modules/express/lib/router/index.js:267:22
   at Function.proto.process_params (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/router/index.js:321:12)
   at next (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/router/index.js:261:10)
   at /Users/Hoiy/project/WikiLogic/controllers/index.js:8:3
   at Layer.handle [as handle_request] (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/Hoiy/project/WikiLogic/node_modules/express/lib/router/index.js:302:13)
```

**Comment by ijmccallum** [comment]
old repo - clearing issues (currently working on signup for the new stuff! Keep an eye on the github org or the website for news on this project actually getting off the ground, we're close (http://www.wikilogicfoundation.org/))
