### ISSUE TITLE
Get demo working

### ISSUE THREAD

**Issue by ijmccallum** [WikiLogic/Server#190]
Sign up fail

**Comment by ijmccallum** [comment]
Just pushed something that should fix the demo... waiting on the build

**Comment by ijmccallum** [comment]
Nope. Things are running, got some log output: 

```
[0;36mMongoose:[0m users.findOne({ [32m'local.email'[39m: [32m'test@test.com'[39m }) { fields: [90mundefined[39m }  
new user!
[0;36mMongoose:[0m users.insert({ _id: ObjectId("574d98b56f07bf1100146cbf"), meta: { gravatar: [32m'//www.gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452'[39m, published: [], trashed: [], unPublished: [] }, local: { password: [32m'$2a$10$KQ6EJC/JptqamBEVJKlpz.VgfadMbIeDV6w7.zRZ1T6UZhcIlZUIK'[39m, email: [32m'test@test.com'[39m }, __v: [33m0[39m })   

 process.nextTick(function() { throw err; });
                               ^
at Callbacks.emit (/app/node_modules/mongodb-core/lib/topologies/server.js:119:3)
at Socket.Readable.push (_stream_readable.js:111:10)
npm ERR! Exit status 1
npm ERR! Failed at the Wikilogic@0.3.0 start script 'node server.js'.
at=error code=H13 desc="Connection closed without response" method=POST path="/signup" host=wikilogic.herokuapp.com request_id=991c1570-d26b-40a0-8e3d-3f1f19a84091 fwd="173.15.136.74" dyno=web.1 connect=1ms service=505ms status=503 bytes=0

```

**Comment by ijmccallum** [comment]
gulp-sass cannot be found, error happens in the gulp file :(

**Comment by ijmccallum** [comment]
Getting closer, now just need to make sure email gets passed to the db on sign up, currently it's coming through as null so we get duplicate key errors. Also should catch that and return the appropriate response.

**Comment by ijmccallum** [comment]
OH MY GOD THAT WAS A NIGHTMARE
